dataset_path = "data/sift-128-euclidean.hdf5"
dimension = 128
top_k = 10
warmup_queries = 100
query_limit = 1000
query_cycles = 100
load_index_prefix = "data/index/sift-128-euclidean-1MLN"
seed = 42

# base_limit = 100000
# save_index_prefix = "data/index/sift-128-euclidean-1MLN"

# defaults
# base_datasets = ["train", "base"]
# query_datasets = ["test", "query", "queries"]
# ground_truth_datasets = ["neighbors", "knns", "groundtruth"]

[[configs]]
m = 16
m0 = 32
ef_construction = 128
ef_search = 32

[[configs]]
m = 16
m0 = 32
ef_construction = 128
ef_search = 64

[[configs]]
m = 32
m0 = 64
ef_construction = 200
ef_search = 64

[[configs]]
m = 32
m0 = 64
ef_construction = 200
ef_search = 128
